application: p3k-001
version: 4
runtime: python
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /roxy
  script: roxy.py
- url: /ferris
  script: ferris.py
- url: /cron/.+
  script: cron.py
  login: admin
  